apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "yrkesinfo-schedulers"
        spec:
          containers:
            - name: "yrkesinfo-schedule"
              image: "${NAMESPACE}/yrkesinfo:latest"
              command: ["php",  "artisan", "schedule:run"]
          restartPolicy: OnFailure